project:
  type: website

website:
  title: "Reliability and Longitudinal Invariance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - license.qmd
      - reliability.qmd
      - test-retest-reliability.qmd
      - longitudinal-invariance.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css

editor: source

