project:
  type: website

website:
  title: "Reliability and Longitudinal Invariance"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "General"
        contents:
          - index.qmd
      - section: "Technical Details"
        contents:
          - reliability.qmd
          - test-retest-reliability.qmd
          - longitudinal-invariance.qmd
      - section: "Demonstration"
        contents:
          - reliability.qmd
          - test-retest-reliability.qmd
          - longitudinal-invariance.qmd
          
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

